DROP TABLE SCREEN_TABLE;

DROP SEQUENCE SCREEN_TABLE_SEQUENCE;

CREATE TABLE SCREEN_TABLE 
(
   	 ID           			NUMBER(4)    	NOT NULL
  	,GROUP_ID				NUMBER(3)    	NOT NULL
	,USER_ID				NUMBER(3)    	NOT NULL
	,SEQ					NUMBER(2)    	NOT NULL
	,MENU_NAME				VARCHAR2(30)    NOT NULL
	,SCREEN_NAME			VARCHAR2(30)    NOT NULL
	,CREATE_OPERATION		NUMBER(1)    	NOT NULL
	,READ_OPERATION			NUMBER(1)    	NOT NULL
	,UPDATE_OPERATION		NUMBER(1)    	NOT NULL
  	,DELETE_OPERATION		NUMBER(1)    	NOT NULL
  	,CREATE_USER			CHAR(8)			NOT NULL
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL
  	,MODIFY_USER			CHAR(8)			NOT NULL
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL
);

ALTER TABLE SCREEN_TABLE ADD (
  CONSTRAINT SCREEN_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE SCREEN_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER SCREEN_TABLE_TRIGGER 
BEFORE INSERT ON SCREEN_TABLE 
FOR EACH ROW

BEGIN
  SELECT SCREEN_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/