DROP TABLE BUSINESS_OVERVIEW_TABLE;

DROP SEQUENCE BUSINESS_OVERVIEW_TABLE_SEQ;

CREATE TABLE BUSINESS_OVERVIEW_TABLE 
(
  	 ID           			NUMBER(4)  		NOT NULL  
	,EFFECTIVE_DATE			DATE			NOT NULL
	,MAJOR_VERSION			NUMBER(2)		NOT NULL
	,MINOR_VERSION			NUMBER(2)		NOT NULL
	,SECTION				NUMBER(2)		NOT NULL
	,SUBSECTION				NUMBER(2)		NOT NULL
	,PARAGRAPH				NUMBER(2)		NOT NULL
	,TITLE					VARCHAR2(50)	NOT NULL	
	,SENTENCE				VARCHAR2(50)	NOT NULL	
  	,CREATE_USER			CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER			CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 
);

ALTER TABLE BUSINESS_OVERVIEW_TABLE ADD (
  CONSTRAINT BUSINESS_OVERVIEW_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE BUSINESS_OVERVIEW_TABLE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER BUSINESS_OVERVIEW_TABLE_TRIG 
BEFORE INSERT ON BUSINESS_OVERVIEW_TABLE 
FOR EACH ROW

BEGIN
  SELECT BUSINESS_OVERVIEW_TABLE_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/