DROP TABLE LETTER_TABLE;

DROP SEQUENCE LETTER_TABLE_SEQUENCE;

CREATE TABLE LETTER_TABLE 
(
   	 ID           			NUMBER(4)   	NOT NULL 	   
	,ASSOCIATION			VARCHAR2(30)	NOT NULL
	,TITLE					VARCHAR2(30)	NOT NULL
	,SUBTITLE				VARCHAR2(30)	NOT NULL
	,VERSION				VARCHAR2(5)		NOT NULL
	,EFFECTIVE_DATE			DATE   			NOT NULL 
	,RELEASE_OVERVIEW		NUMBER(2)   	NOT NULL 	
	,SECTION				NUMBER(2)   	NOT NULL 	
	,APPENDIX				NUMBER(2)   	NOT NULL 	
  	,CREATE_USER			CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER			CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL		 
);

ALTER TABLE LETTER_TABLE ADD (
  CONSTRAINT LETTER_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE LETTER_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER LETTER_TABLE_TRIGGER 
BEFORE INSERT ON LETTER_TABLE 
FOR EACH ROW

BEGIN
  SELECT LETTER_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/