DROP TABLE MESSAGE_TYPE_IMPACT_TABLE;

DROP SEQUENCE MESSAGE_TYPE_IMPACT_TABLE_SEQ;

CREATE TABLE MESSAGE_TYPE_IMPACT_TABLE
(
  	 ID           			NUMBER(4)  		NOT NULL  
	,EFFECTIVE_DATE			DATE			NOT NULL
	,MAJOR_VERSION			NUMBER(2)		NOT NULL
	,MINOR_VERSION			NUMBER(2)		NOT NULL
	,SECTION				NUMBER(2)		NOT NULL
	,SUBSECTION				NUMBER(2)		NOT NULL
	,PARAGRAPH				NUMBER(2)		NOT NULL
	,MESSAGE_TYPE			CHAR(4)			NOT NULL	
	,IMPACT					NUMBER(1)		NOT NULL
  	,CREATE_USER			CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER			CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 	  
);

ALTER TABLE MESSAGE_TYPE_IMPACT_TABLE ADD (
  CONSTRAINT MESSAGE_TYPE_IMPACT_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE MESSAGE_TYPE_IMPACT_TABLE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER MESSAGE_TYPE_IMPACT_TABLE_TRIG 
BEFORE INSERT ON MESSAGE_TYPE_IMPACT_TABLE 
FOR EACH ROW

BEGIN
  SELECT MESSAGE_TYPE_IMPACT_TABLE_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/