DROP TABLE REGION_IMPACT_TABLE;

DROP SEQUENCE REGION_IMPACT_TABLE_SEQUENCE;

CREATE TABLE REGION_IMPACT_TABLE
(
  	 ID           			NUMBER(4)  		NOT NULL  
	,EFFECTIVE_DATE			DATE			NOT NULL
	,MAJOR_VERSION			NUMBER(2)		NOT NULL
	,MINOR_VERSION			NUMBER(2)		NOT NULL
	,SECTION				NUMBER(2)		NOT NULL
	,SUBSECTION				NUMBER(2)		NOT NULL
	,PARAGRAPH				NUMBER(2)		NOT NULL
	,REGION					VARCHAR2(30)	NOT NULL	
	,IMPACT					NUMBER(1)		NOT NULL
  	,CREATE_USER			CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER			CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 	 
);

ALTER TABLE REGION_IMPACT_TABLE ADD (
  CONSTRAINT REGION_IMPACT_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE REGION_IMPACT_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER REGION_IMPACT_TABLE_TRIGGER 
BEFORE INSERT ON REGION_IMPACT_TABLE 
FOR EACH ROW

BEGIN
  SELECT REGION_IMPACT_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/