DROP TABLE RELATED_DOCUMENT_TABLE;

DROP SEQUENCE RELATED_DOCUMENT_TBL_SEQUENCE;

CREATE TABLE RELATED_DOCUMENT_TABLE
(
   	 ID           		NUMBER(4)  		NOT NULL  
   	,SEQ          		NUMBER(2)  		NOT NULL  
	,DOCUMENT			VARCHAR2(30)	NOT NULL	 
	,VERSION			VARCHAR2(5)		NOT NULL	
	,AUTHOR				VARCHAR2(30)	NOT NULL	 
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
);

ALTER TABLE RELATED_DOCUMENT_TABLE ADD (
  CONSTRAINT RELATED_DOCUMENT_TABLE_PK PRIMARY KEY (ID,SEQ));

CREATE SEQUENCE RELATED_DOCUMENT_TBL_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER RELATED_DOCUMENT_TABLE_TRIGGER 
BEFORE INSERT ON RELATED_DOCUMENT_TABLE 
FOR EACH ROW

BEGIN
  SELECT RELATED_DOCUMENT_TBL_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/