DROP TABLE RELEASE_OVERVIEW_TABLE;

DROP SEQUENCE RELEASE_OVERVIEW_TBL_SEQUENCE;

CREATE TABLE RELEASE_OVERVIEW_TABLE
(
   	 ID           		NUMBER(4)  		NOT NULL
   	,SEQ				NUMBER(2)		NOT NULL	
	,DATE_FIELD			DATE			NOT NULL	 
	,EVENT				VARCHAR2(30)	NOT NULL	
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
);

ALTER TABLE RELEASE_OVERVIEW_TABLE ADD (
  CONSTRAINT RELEASE_OVERVIEW_TABLE_PK PRIMARY KEY (ID,SEQ));

CREATE SEQUENCE RELEASE_OVERVIEW_TBL_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER RELEASE_OVERVIEW_TABLE_TRIGGER 
BEFORE INSERT ON RELEASE_OVERVIEW_TABLE 
FOR EACH ROW

BEGIN
  SELECT RELEASE_OVERVIEW_TBL_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/