DROP TABLE SECTION_TABLE;

DROP SEQUENCE SECTION_SEQUENCE;

CREATE TABLE SECTION_TABLE
(
   	 ID           		NUMBER(4)  		NOT NULL  
	,TITLE				VARCHAR2(50)	NOT NULL	
	,EFFECTIVE_DATE		DATE			NOT NULL
	,MAJOR_VERSION		NUMBER(2)		NOT NULL
	,MINOR_VERSION		NUMBER(2)		NOT NULL
	,SECTION			NUMBER(2)		NOT NULL
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	  
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 	 
);

ALTER TABLE SECTION_TABLE ADD (
  CONSTRAINT SECTION_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE SECTION_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER SECTION_TABLE_TRIGGER 
BEFORE INSERT ON SECTION_TABLE 
FOR EACH ROW

BEGIN
  SELECT SECTION_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/