DROP TABLE SYSTEM_IMPACT_TABLE;

DROP SEQUENCE SYSTEM_IMPACT_TABLE_SEQUENCE;

CREATE TABLE SYSTEM_IMPACT_TABLE
(
  	 ID           			NUMBER(4)  		NOT NULL  
	,EFFECTIVE_DATE			DATE			NOT NULL
	,MAJOR_VERSION			NUMBER(2)		NOT NULL
	,MINOR_VERSION			NUMBER(2)		NOT NULL
	,SECTION				NUMBER(2)		NOT NULL
	,SUBSECTION				NUMBER(2)		NOT NULL
	,PARAGRAPH				NUMBER(2)		NOT NULL
	,SYSTEM					VARCHAR2(10)	NOT NULL	
	,TESTING_AVAILABLE		NUMBER(1)		NOT NULL
	,TESTING_REQUIRED		NUMBER(1)		NOT NULL
	,ACTIVATION_REQUIRED	NUMBER(1)		NOT NULL
  	,CREATE_USER			CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER			CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 
);

ALTER TABLE SYSTEM_IMPACT_TABLE ADD (
  CONSTRAINT SYSTEM_IMPACT_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE SYSTEM_IMPACT_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER SYSTEM_IMPACT_TABLE_TRIGGER 
BEFORE INSERT ON SYSTEM_IMPACT_TABLE 
FOR EACH ROW

BEGIN
  SELECT SYSTEM_IMPACT_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/