DROP TABLE USAGE_TABLE;

DROP SEQUENCE USAGE_TABLE_SEQUENCE;

CREATE TABLE USAGE_TABLE 
(
  	 ID           			NUMBER(4)  		NOT NULL  
	,EFFECTIVE_DATE			DATE			NOT NULL
	,MAJOR_VERSION			NUMBER(2)		NOT NULL
	,MINOR_VERSION			NUMBER(2)		NOT NULL
	,SECTION				NUMBER(2)		NOT NULL
	,SUBSECTION				NUMBER(2)		NOT NULL
	,PARAGRAPH				NUMBER(2)		NOT NULL
	,SENTENCE				NUMBER(2)		NOT NULL
	,SYSTEM           		VARCHAR2(20)   	NOT NULL 
	,REGION           		VARCHAR2(20)   	NOT NULL 
	,PLATFORM           	VARCHAR2(20)   	NOT NULL 
	,PROCESSING           	VARCHAR2(10)   	NOT NULL 
	,MESSAGE_TYPE			CHAR(4)			NOT NULL
	,STATUS           		NUMBER(1)   	NOT NULL 
  	,CREATE_USER			CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER			CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 
);

ALTER TABLE USAGE_TABLE ADD (
  CONSTRAINT USAGE_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE USAGE_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER USAGE_TABLE_TRIGGER 
BEFORE INSERT ON USAGE_TABLE 
FOR EACH ROW

BEGIN
  SELECT USAGE_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/