DROP TABLE VALID_CODE_TABLE;

DROP SEQUENCE VALID_CODE_TABLE_SEQUENCE;

CREATE TABLE VALID_CODE_TABLE 
(
   	 ID           			NUMBER(4)   	NOT NULL 	   
	,FIELD					NUMBER(3)   	NOT NULL 
	,SUBFIELD				NUMBER(2)   	NOT NULL 	
	,SEQ           			NUMBER(2)   	NOT NULL 	  
	,CODE					CHAR(4)			NOT NULL
	,NAME					VARCHAR2(30)	NOT NULL
	,DESCRIPTION			VARCHAR2(30)	NOT NULL
  	,CREATE_USER			CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL 
  	,MODIFY_USER			CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL		 
);

ALTER TABLE VALID_CODE_TABLE ADD (
  CONSTRAINT VALID_CODE_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE VALID_CODE_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER VALID_CODE_TABLE_TRIGGER 
BEFORE INSERT ON VALID_CODE_TABLE 
FOR EACH ROW

BEGIN
  SELECT VALID_CODE_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/