DROP TABLE TEMPLATE_TABLE;

DROP SEQUENCE TEMPLATE_TABLE_SEQUENCE;

CREATE TABLE TEMPLATE_TABLE 
(
   	 ID           						NUMBER(4)    	NOT NULL
	,PROCESSING_CODE					CHAR(6)			NOT NULL
  	,POINT_OF_SERVICE_ENTRY_MODE		CHAR(3)			NOT NULL
	,POINT_OF_SERVICE_CONDITON_CODE		NUMBER(2)		NOT NULL
  	,PRIMARY_ACCOUNT_NUMBER				VARCHAR2(19)	NOT NULL
	,MERCHANT_TYPE						NUMBER(4)		NOT NULL	
  	,EXPIRATION_DATE					DATE			NOT NULL
	,TRACK2_DATA						VARCHAR2(37)	NOT NULL	
	,TRANSACTION_AMOUNT					NUMBER(12)		NOT NULL
  	,ADDITIONAL_AMOUNTS					VARCHAR2(120)	NOT NULL
  	,PERSONAL_IDENTIFICATION_NUMBER		NUMBER(4)		NOT NULL
	,RESPONSE_CODE						VARCHAR2(2)		NOT NULL	
   	,CREATE_USER						CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP					TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER						CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP					TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE TEMPLATE_TABLE ADD (
  CONSTRAINT TEMPLATE_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE TEMPLATE_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER TEMPLATE_TABLE_TRIGGER 
BEFORE INSERT ON TEMPLATE_TABLE 
FOR EACH ROW

BEGIN
  SELECT TEMPLATE_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/