DROP TABLE VALIDATE_DETAIL_TABLE;

DROP SEQUENCE VALIDATE_DETAIL_TABLE_SEQUENCE;

CREATE TABLE VALIDATE_DETAIL_TABLE 
(
   	 ID           		NUMBER(4)    	NOT NULL
  	,FIELD				NUMBER(3)    	NOT NULL
	,SUBFIELD			NUMBER(2)    	NOT NULL
	,FIRE				NUMBER(3)    	NOT NULL
  	,VALIDATE_TYPE		NUMBER(3)    	NOT NULL
  	,VALIDATE_GROUP		NUMBER(3)    	NOT NULL
  	,BIN_LEVEL			NUMBER(3)    	NOT NULL
  	,ACCOUNT_LEVEL		NUMBER(3)    	NOT NULL
  	,TRANSACTION_LEVEL	NUMBER(3)    	NOT NULL
  	,POINTER			NUMBER(3)    	NOT NULL
  	,SEQ				NUMBER(3)    	NOT NULL
  	,FIELD_VALUE		NUMBER(3)    	NOT NULL
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE VALIDATE_DETAIL_TABLE ADD (
  CONSTRAINT VALIDATE_DETAIL_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE VALIDATE_DETAIL_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER VALIDATE_DETAIL_TABLE_TRIGGER 
BEFORE INSERT ON VALIDATE_DETAIL_TABLE 
FOR EACH ROW

BEGIN
  SELECT VALIDATE_DETAIL_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/