DROP TABLE AMOUNT_TABLE;

DROP SEQUENCE AMOUNT_TABLE_SEQUENCE;

CREATE TABLE AMOUNT_TABLE 
(
   	 ID           							NUMBER(4)    	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER					VARCHAR2(19)	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER_SEQ				NUMBER(2)		NOT NULL   
   	,CURRENCY_CODE_APPLICATION				NUMBER(3)		NOT NULL
   	,CURRENCY_CONVERSION_FACTOR				NUMBER(8)		NOT NULL 
	,CURRENCY_EXPONENT_APPLICATION			NUMBER(1)		NOT NULL
	,SECONDARY_APPL_CURRENCY_CODE			NUMBER(3)		NOT NULL 
	,CONSECUT_DOM_OFFLINE_CTR				NUMBER(1)		NOT NULL
	,CONSECUT_DOM_OFFLINE_LWR_LMT			NUMBER(1)		NOT NULL
	,CONSECUT_DOM_OFFLINE_UPR_LMT			NUMBER(1)		NOT NULL
	,CONSECUT_INTL_OFFLINE_CTR				NUMBER(1)		NOT NULL
	,CONSECUT_INTL_OFFLINE_LWR_LMT			NUMBER(1)		NOT NULL
	,CONSECUT_INTL_OFFLINE_UPR_LMT			NUMBER(1)		NOT NULL	
   	,CUM_TOT_DOM_TRANS_AMOUNT				NUMBER(12)		NOT NULL 
   	,CUM_TOT_DOM_TRANS_AMT_LWR_LMT			NUMBER(12)		NOT NULL 
   	,CUM_TOT_DOM_TRANS_AMT_UPR_LMT			NUMBER(12)		NOT NULL  
   	,CUM_TOT_INTL_TRANS_AMOUNT				NUMBER(12)		NOT NULL 
   	,CUM_TOT_INTL_TRANS_AMT_LWR_LMT			NUMBER(12)		NOT NULL 
   	,CUM_TOT_INTL_TRANS_AMT_UPR_LMT			NUMBER(12)		NOT NULL   
   	,ENCRYPTED_PIN							NUMBER(4)		NOT NULL 
   	,PIN_TRY_COUNTER						NUMBER(1)		NOT NULL  
  	,CREATE_USER							CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP						TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER							CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP						TIMESTAMP(4)	NOT NULL		
);

ALTER TABLE AMOUNT_TABLE ADD (
  CONSTRAINT AMOUNT_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE AMOUNT_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER AMOUNT_TABLE_TRIGGER 
BEFORE INSERT ON AMOUNT_TABLE 
FOR EACH ROW

BEGIN
  SELECT AMOUNT_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/