DROP TABLE APPLICATION_TABLE;

DROP SEQUENCE APPLICATION_TABLE_SEQUENCE;

CREATE TABLE APPLICATION_TABLE 
(
   	 ID           					NUMBER(4)    	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER			VARCHAR2(19)	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER_SEQ		NUMBER(2)		NOT NULL
   	,APPLICATION_VERSION_NUMBER		NUMBER(2)		NOT NULL	 			
	,APPLICATION_USAGE_CONTROL		NUMBER(2)		NOT NULL	 			 
	,APPLICATION_CRYPTOGRAM			NUMBER(8)		NOT NULL
	,UNPREDICTABLE_NUMBER			NUMBER(8)		NOT NULL	 
	,CRYPTOGRAM_INFORMATION_DATA	NUMBER(1)		NOT NULL	 			 
	,LAST_ONLINE_TRANS_COUNTER		NUMBER(2)		NOT NULL	 			 
	,APPLICATION_TRANS_COUNTER		NUMBER(2)		NOT NULL
	,APPLICATION_EFFECTIVE_DATE		DATE			NOT NULL
 	,APPLICATION_EXPIRATION_DATE	DATE			NOT NULL	 	
  	,CREATE_USER					CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP				TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER					CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP				TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE APPLICATION_TABLE ADD (
  CONSTRAINT APPLICATION_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE APPLICATION_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER APPLICATION_TABLE_TRIGGER 
BEFORE INSERT ON APPLICATION_TABLE 
FOR EACH ROW

BEGIN
  SELECT APPLICATION_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/