DROP TABLE ISSUER_TABLE;

DROP SEQUENCE ISSUER_TABLE_SEQUENCE;

CREATE TABLE ISSUER_TABLE 
(
   	 ID           					NUMBER(4)    	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER			VARCHAR2(19)	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER_SEQ		NUMBER(2)		NOT NULL
 	,INTL_BANK_ACCOUNT_NUMBER		VARCHAR2(34)	NOT NULL
 	,BANK_IDENTIFIER_CODE			VARCHAR2(11)	NOT NULL
 	,BANK_IDENTIFICATION_NUMBER		NUMBER(6)		NOT NULL	
 	,MERCHANT_CATEGORY_CODE			CHAR(4)			NOT NULL
 	,MERCHANT_IDENTIFIER			VARCHAR2(15)	NOT NULL 	
	,COUNTRY_CODE					CHAR(3)			NOT NULL
	,ACTION_CODE_DEFAULT			NUMBER(5)		NOT NULL
	,ACTION_CODE_DENIAL				NUMBER(5)		NOT NULL
	,ACTION_CODE_ONLINE				NUMBER(5)		NOT NULL	
	,PUBLIC_KEY_CERTIFICATE			VARCHAR2(176)	NOT NULL
	,PUBLIC_KEY_EXPONENT			NUMBER(3)		NOT NULL
	,PUBLIC_KEY_REMAINDER			NUMBER(36)		NOT NULL	
  	,CREATE_USER					CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP				TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER					CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP				TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE ISSUER_TABLE ADD (
  CONSTRAINT ISSUER_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE ISSUER_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER ISSUER_TABLE_TRIGGER 
BEFORE INSERT ON ISSUER_TABLE 
FOR EACH ROW

BEGIN
  SELECT ISSUER_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/