DROP TABLE VERIFICATION_TABLE;

DROP SEQUENCE VERIFICATION_TABLE_SEQUENCE;

CREATE TABLE VERIFICATION_TABLE 
(
   	 ID           					NUMBER(4)    	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER			VARCHAR2(19)	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER_SEQ		NUMBER(2)		NOT NULL
   	,CARDHLDR_VERIFICATION_METHOD	NUMBER(2)		NOT NULL
   	,CARDHLDR_VERIFICATION_STATUS	NUMBER(1)		NOT NULL
  	,CREATE_USER					CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP				TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER					CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP				TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE VERIFICATION_TABLE ADD (
  CONSTRAINT VERIFICATION_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE VERIFICATION_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER VERIFICATION_TABLE_TRIGGER 
BEFORE INSERT ON VERIFICATION_TABLE 
FOR EACH ROW

BEGIN
  SELECT VERIFICATION_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/