DROP TABLE CURRENCY_TABLE;

DROP SEQUENCE CURRENCY_TABLE_SEQUENCE;

CREATE TABLE CURRENCY_TABLE 
(
   	 ID           						NUMBER(4)    	NOT NULL
	,ACQUIRER_IDENTIFIER				NUMBER(11)    	NOT NULL
	,MERCHANT_IDENTIFIER				VARCHAR2(15)   	NOT NULL
	,TERMINAL_IDENTIFICATION			VARCHAR2(8)    	NOT NULL
	,ACCOUNT_TYPE						NUMBER(2)    	NOT NULL
	,AMOUNT_AUTHORIZED					NUMBER(12)    	NOT NULL
	,AMOUNT_OTHER						NUMBER(12)    	NOT NULL
	,AMOUNT_REFERENCE_CURRENCY			NUMBER(4)    	NOT NULL
	,CODE_TRANS_REFERENCE_CODE			NUMBER(3)    	NOT NULL
	,EXPONENT_TRANS_REFERENCE			NUMBER(1)    	NOT NULL
  	,CREATE_USER						CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP					TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER						CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP					TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE CURRENCY_TABLE ADD (
  CONSTRAINT CURRENCY_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE CURRENCY_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER CURRENCY_TABLE_TRIGGER 
BEFORE INSERT ON CURRENCY_TABLE 
FOR EACH ROW

BEGIN
  SELECT CURRENCY_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/