DROP TABLE TERMINAL_TABLE;

DROP SEQUENCE TERMINAL_TABLE_SEQUENCE;

CREATE TABLE TERMINAL_TABLE 
(
   	 ID           						NUMBER(4)    	NOT NULL
	,ACQUIRER_IDENTIFIER				NUMBER(11)    	NOT NULL
	,MERCHANT_IDENTIFIER				VARCHAR2(15)   	NOT NULL
	,TERMINAL_IDENTIFICATION			VARCHAR2(8)    	NOT NULL
	,MERCHANT_CATEGORY_CODE				NUMBER(4)    	NOT NULL
	,MERCHANT_NAME_AND_LOCATION			VARCHAR2(4)    	NOT NULL
	,INTERFACE_DEVICE_SERIAL_NUMBER		VARCHAR2(8)    	NOT NULL
	,TERMINAL_TYPE						NUMBER(2)    	NOT NULL
	,TERMINAL_COUNTRY_CODE				NUMBER(3)    	NOT NULL
	,TERMINAL_CAPABILITIES				NUMBER(1)    	NOT NULL
	,KERNEL_4_READER_CAPABILITIES		NUMBER(1)    	NOT NULL
	,ADDITIONAL_TERM_CAPABILITIES		NUMBER(1)    	NOT NULL
	,TERMINAL_TRANS_QUALIFIER			NUMBER(4)    	NOT NULL
	,VLP_TERM_SUPPORT_INDICATOR			NUMBER(1)    	NOT NULL
	,VLP_TERM_TRANSACTION_LIMIT			NUMBER(4)    	NOT NULL
	,TERMINAL_FLOOR_LIMIT				NUMBER(4)    	NOT NULL
	,ACTION_CODE_DEFAULT				NUMBER(1)    	NOT NULL
	,ACTION_CODE_DECLINE				NUMBER(1)    	NOT NULL
	,ACTION_CODE_ONLINE					NUMBER(1)    	NOT NULL
	,RISK_MANAGEMENT_DATA				NUMBER(1)    	NOT NULL
	,VERIFICATION_RESULTS				NUMBER(1)    	NOT NULL
  	,CREATE_USER						CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP					TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER						CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP					TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE TERMINAL_TABLE ADD (
  CONSTRAINT TERMINAL_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE TERMINAL_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER TERMINAL_TABLE_TRIGGER 
BEFORE INSERT ON TERMINAL_TABLE 
FOR EACH ROW

BEGIN
  SELECT TERMINAL_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/