DROP TABLE TRANSACTION_TABLE;

DROP SEQUENCE TRANSACTION_TABLE_SEQUENCE;

CREATE TABLE TRANSACTION_TABLE 
(
   	 ID           					NUMBER(4)    	NOT NULL
	,ACQUIRER_IDENTIFIER			NUMBER(11)    	NOT NULL
	,MERCHANT_IDENTIFIER			VARCHAR2(15)   	NOT NULL
	,TRANSACTION_IDENTIFICATION		VARCHAR2(8)    	NOT NULL
	,STATUS_INFORMATION				NUMBER(4)    	NOT NULL
	,FORM_FACTOR_INDICATOR			CHAR(4)    		NOT NULL
	,POINT_OF_SERVICE_ENTRY_MODE	CHAR(2)    		NOT NULL
	,TRANSACTION_PIN				NUMBER(4)    	NOT NULL
	,TRANSACTON_TYPE				NUMBER(2)    	NOT NULL
	,TRANSACTION_DATE				NUMBER(6)    	NOT NULL
	,TRANSACTION_TIME				NUMBER(6)    	NOT NULL
	,COUNTRY_CODE					NUMBER(3)    	NOT NULL
	,CURRENCY_CODE					NUMBER(3)    	NOT NULL
	,CURRENCY_EXPONENT				NUMBER(1)    	NOT NULL
	,REFERENCE_CURRENCY_CODE		NUMBER(3)    	NOT NULL
	,REFERENCE_CURRENCY_EXPONENT	NUMBER(1)    	NOT NULL
	,TRANSACTION_CERTIFICATE		NUMBER(4)    	NOT NULL
	,AUTHORIZATION_RESPONSE_CODE	CHAR(2)    		NOT NULL
	,SEQUENCE_COUNTER				NUMBER(8)    	NOT NULL
  	,CREATE_USER					CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP				TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER					CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP				TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE TRANSACTION_TABLE ADD (
  CONSTRAINT TRANSACTION_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE TRANSACTION_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER TRANSACTION_TABLE_TRIGGER 
BEFORE INSERT ON TRANSACTION_TABLE 
FOR EACH ROW

BEGIN
  SELECT TRANSACTION_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/