DROP TABLE MENU_TABLE;

DROP SEQUENCE MENU_TABLE_SEQUENCE;

CREATE TABLE MENU_TABLE 
(
   	 ID           			NUMBER(4)    	NOT NULL
  	,GROUP_ID				NUMBER(3)    	NOT NULL
	,USER_ID				NUMBER(3)    	NOT NULL
	,SEQ					NUMBER(2)    	NOT NULL
	,PARENT_MENU			VARCHAR2(30)    NOT NULL
  	,CHILD_MENU				VARCHAR2(50)    NOT NULL
  	,PROFILE_STATUS			NUMBER(1)    	NOT NULL
  	,PARENT_MENU_STATUS		NUMBER(1)    	NOT NULL
  	,VIEW_JSP_PATH			VARCHAR2(40)    NOT NULL
  	,CHILD_MENU_STATUS		NUMBER(1)    	NOT NULL
  	,CREATE_USER			CHAR(8)			NOT NULL
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL
  	,MODIFY_USER			CHAR(8)			NOT NULL
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL
);

ALTER TABLE MENU_TABLE ADD (
  CONSTRAINT MENU_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE MENU_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER MENU_TABLE_TRIGGER 
BEFORE INSERT ON MENU_TABLE 
FOR EACH ROW

BEGIN
  SELECT MENU_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/