DROP TABLE FEMALE_FIRST_NAME_TABLE;

DROP SEQUENCE FEMALE_FIRST_NAME_TABLE_SEQ;

CREATE TABLE FEMALE_FIRST_NAME_TABLE 
(
   	 ID           		NUMBER(4)    	NOT NULL
	,FIRST_NAME			VARCHAR2(30)	NOT NULL
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL		
);

ALTER TABLE FEMALE_FIRST_NAME_TABLE ADD (
  CONSTRAINT FEMALE_FIRST_NAME_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE FEMALE_FIRST_NAME_TABLE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FEMALE_FIRST_NAME_TBL_TRIGGER 
BEFORE INSERT ON FEMALE_FIRST_NAME_TABLE 
FOR EACH ROW

BEGIN
  SELECT FEMALE_FIRST_NAME_TABLE_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/