DROP TABLE MALE_FIRST_NAME_TABLE;

DROP SEQUENCE MALE_FIRST_NAME_TABLE_SEQUENCE;

CREATE TABLE MALE_FIRST_NAME_TABLE 
(
   	 ID           		NUMBER(4)    	NOT NULL
	,FIRST_NAME			VARCHAR2(30)	NOT NULL
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL		
);

ALTER TABLE MALE_FIRST_NAME_TABLE ADD (
  CONSTRAINT MALE_FIRST_NAME_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE MALE_FIRST_NAME_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER MALE_FIRST_NAME_TABLE_TRIGGER 
BEFORE INSERT ON MALE_FIRST_NAME_TABLE 
FOR EACH ROW

BEGIN
  SELECT MALE_FIRST_NAME_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/