DROP TABLE ACQUIRER_MASTER_FILE_TABLE;

DROP SEQUENCE ACQUIRER_MASTER_FILE_TABLE_SEQ;

CREATE TABLE ACQUIRER_MASTER_FILE_TABLE 
(
   	 ID           					NUMBER(4)    	NOT NULL
   	,INTL_BANK_ACCOUNT_NUMBER		VARCHAR2(34)	NOT NULL
   	,BANK_IDENTIFIER_CODE			VARCHAR2(11)	NOT NULL
   	,BANK_IDENTIFICATION_NUMBER		NUMBER(6)		NOT NULL 
	,MERCHANT_IDENTIFIER			VARCHAR2(15)	NOT NULL
	,MERCHANT_CATEGORY_CODE			CHAR(4)			NOT NULL
	,ACQUIRER_IDENTIFIER			NUMBER(11)		NOT NULL
	,TERMINAL_IDENTIFICATION		CHAR(8)			NOT NULL						
	,INTERFACE_DEVICE_SERIAL_NUMBER	CHAR(8)			NOT NULL
	,TERMINAL_TYPE					NUMBER(2)		NOT NULL
	,TERMINAL_COUNTRY_CODE			NUMBER(3)		NOT NULL
	,COUNTRY_CODE					NUMBER(3)		NOT NULL
	,CURRENCY_CODE					NUMBER(3)		NOT NULL
	,FORM_FACTOR_INDICATOR			NUMBER(4)		NOT NULL
	,POINT_OF_SERVICE_ENTRY_MODE	NUMBER(2)		NOT NULL
	,TRANSACTON_TYPE				NUMBER(2)		NOT NULL
	,TRANSACTION_DATE				NUMBER(6)		NOT NULL
	,TRANSACTION_TIME				NUMBER(6)		NOT NULL		
  	,CREATE_USER					CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP				TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER					CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP				TIMESTAMP(4)	NOT NULL
);

ALTER TABLE ACQUIRER_MASTER_FILE_TABLE ADD (
  CONSTRAINT ACQUIRER_MASTER_FILE_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE ACQUIRER_MASTER_FILE_TABLE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER ACQ_MASTER_FILE_TABLE_TRIGGER
BEFORE INSERT ON ACQUIRER_MASTER_FILE_TABLE 
FOR EACH ROW

BEGIN
  SELECT ACQUIRER_MASTER_FILE_TABLE_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/