delete from CARDHOLDER_NAME_TABLE;

-- United States

insert into CARDHOLDER_NAME_TABLE values ( 0, 'James'		, 'Smith'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'John'		, 'Johnson'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Robert'		, 'Williams'	, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Michael'		, 'Jones'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'William'		, 'Brown'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'David'		, 'Davis'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Richard'		, 'Miller'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Joseph'		, 'Wilson'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Thomas'		, 'Moore'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Charles'		, 'Taylor'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Mary'		, 'Smith'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Patricia'	, 'Johnson'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jennifer'	, 'Williams'	, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Linda'		, 'Jones'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Elizabeth'	, 'Brown'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Barbara'		, 'Davis'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Susan'		, 'Miller'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jessica'		, 'Wilson'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sarah'		, 'Moore'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Margaret'	, 'Taylor'		, '840', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

-- Great Britain

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Oliver'		, 'Smith'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Harry'		, 'Jones'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'George'		, 'Williams'	, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jack'		, 'Taylor'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jacob'		, 'Davies'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Noah'		, 'Evans'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Charlie'		, 'Wilson'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Thomas'		, 'Walker'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Oscar'		, 'Thomas'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'William'		, 'Johnson'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Olivia'		, 'Smith'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sophia'		, 'Jones'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Amelia'		, 'Williams'	, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Lily'		, 'Taylor'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Emily'		, 'Davies'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Ava'			, 'Evans'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Isla'		, 'Wilson'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Isabella'	, 'Walker'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Mia'			, 'Thomas'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Isabelle'	, 'Johnson'		, '826', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

-- Canada

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Liam'		, 'Smith'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jackson'		, 'Brown'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Logan'		, 'Tremblay'	, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Lucas'		, 'Martin'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Noah'		, 'Roy'			, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Ethan'		, 'Wilson'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jack'		, 'MacDonald'	, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'William'		, 'Gagnon'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jacob'		, 'Johnson'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'James'		, 'Taylor'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Ava'			, 'Smith'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Olivia'		, 'Brown'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Emma'		, 'Tremblay'	, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Charlotte'	, 'Martin'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sadie'		, 'Roy'			, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Abigail'		, 'Wilson'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Amelita'		, 'MacDonald'	, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Emily'		, 'Gagnon'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Scarlett'	, 'Johnson'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sophia'		, 'Taylor'		, '124', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

-- Italian

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Francesco'	, 'Rossi'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Alessandro'	, 'Bianchi'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Andrea'		, 'Ricci'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Lorenzo'		, 'Marino'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Mattia'		, 'Moretti'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Matteo'		, 'Bruno'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Gabriele'	, 'Esposito'	, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Leonardo'	, 'Colombo'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Riccardo'	, 'Ferrari'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Tommaso'		, 'Romano'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sofia'		, 'Rossi'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Giulia'		, 'Bianchi'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Aurora'		, 'Ricci'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Emma'		, 'Marino'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Giorgia'		, 'Moretti'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Martina'		, 'Bruno'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Chiara'		, 'Esposito'	, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sara'		, 'Colombo'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Alice'		, 'Ferrari'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Gaia'		, 'Romano'		, '380', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

-- Chinese

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Andrew'		, 'Li'			, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Amy'			, 'Wang'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Dan'			, 'Zhang'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Peter'		, 'Liu'			, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Albert'		, 'Chen'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Eric'		, 'Yang'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Alan'		, 'Zhao'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sam'			, 'Huang'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Alex'		, 'Zhou'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'David'		, 'Wu'			, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Amy'			, 'Li'			, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jenny'		, 'Wang'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Grace'		, 'Zhang'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'May'			, 'Liu'			, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Vivian'		, 'Chen'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Alice'		, 'Yang'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jennifer'	, 'Zhao'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Cecilia'		, 'Huang'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jane'		, 'Zhou'		, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Cindy'		, 'Wu'			, '156', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

-- Mexico

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Alejandro'	, 'Garcia'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Eduardo'		, 'Fernandez'	, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Carlos'		, 'Lopez'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jorge'		, 'Martinez'	, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sergio'		, 'Gonzalez'	, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Juan'		, 'Rodriguez'	, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'José'		, 'Sanchez'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Fernando'	, 'Morales'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Enrique'		, 'Cabrera'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Roberto'		, 'Ramirez'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Andrea'		, 'Garcia'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Daniela'		, 'Fernandez'	, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Marisol'		, 'Lopez'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Cristina'	, 'Martinez'	, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Mariana'		, 'Gonzalez'	, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Fernanda'	, 'Rodriguez'	, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Adriana'		, 'Sanchez'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Alejandra'	, 'Morales'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Guadalupe'	, 'Cabrera'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Maria'		, 'Ramirez'		, '484', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

-- France

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Gabriel'		, 'Dubois'		, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Raphael'		, 'Lacroix'		, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Alexandre'	, 'Bertrand'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Antoine'		, 'Fournier'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Gaspard'		, 'Lefevre'		, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Augustin'	, 'Francois'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Camille'		, 'Rousseau'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Gustave'		, 'Fontaine'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Pierre'		, 'Chevalier'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Marceau'		, 'Bourdon'		, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Louise'		, 'Dubois'		, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Chloe'		, 'Lacroix'		, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Heloise'		, 'Bertrand'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Adele'		, 'Fournier'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Juliette'	, 'Lefevre'		, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sofia'		, 'Francois'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Margaux'		, 'Rousseau'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Gabrielle'	, 'Fontaine'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Mathilda'	, 'Chevalier'	, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Madeleine'	, 'Bourdon'		, '250', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

-- German

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jonas'		, 'Muller'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Elias'		, 'Schmidt'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Lukas'		, 'Schneider'	, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Jakob'		, 'Fischer'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Niklas'		, 'Schafer'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Oskar'		, 'Wagner'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Linus'		, 'Schulz'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Johannes'	, 'Neumann'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sebastian'	, 'Dietrich'	, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Fabian'		, 'Lorenz'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Hannah'		, 'Muller'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sophie'		, 'Schmidt'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Frieda'		, 'Schneider'	, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Mathilda'	, 'Fischer'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Greta'		, 'Schafer'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Katharina'	, 'Wagner'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Annika'		, 'Schulz'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Zoey'		, 'Neumann'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Marie'		, 'Dietrich'	, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Valentina'	, 'Lorenz'		, '276', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

-- India

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Rahul'		, 'Gupta'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Deepak'		, 'Singh'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Rakesh'		, 'Chandra'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Kumar'		, 'Ahuja'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Prashant'	, 'Anand'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sunil'		, 'Chopra'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Avinash'		, 'Patel'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Suresh'		, 'Reddy'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Vinay'		, 'Kapoor'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Raju'		, 'Chowdhury'	, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Priya'		, 'Gupta'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Anjali'		, 'Singh'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Gayatri'		, 'Chandra'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Lakshmi'		, 'Ahuja'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Ishita'		, 'Anand'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Aaliyah'		, 'Chopra'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Meera'		, 'Patel'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Manjira'		, 'Reddy'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Noor'		, 'Kapoor'		, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Preet'		, 'Chowdhury'	, '356', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

-- Russian

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Alexei'		, 'Ivanov'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Anatoly'		, 'Smirnov'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Pavel'		, 'Kuznetsov'	, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Anton'		, 'Popov'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Vasily'		, 'Vasiliev'	, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Viktor'		, 'Petrov'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sergei'		, 'Sokolov'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Dimitry'		, 'Mikhailov'	, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Mikhail'		, 'Fedorov'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Leonid'		, 'Morozov'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

insert into CARDHOLDER_NAME_TABLE values ( 0, 'Alexei'		, 'Anastasiya'	, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Anatoly'		, 'Ekaterina'	, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Pavel'		, 'Izabella'	, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Anton'		, 'Ludmila'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Vasily'		, 'Malvina'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Viktor'		, 'Oksana'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Sergei'		, 'Raisa'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Dimitry'		, 'Svetlana'	, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Mikhail'		, 'Sofia'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);
insert into CARDHOLDER_NAME_TABLE values ( 0, 'Leonid'		, 'Tatyana'		, '643', 'TALEXAND', CURRENT_TIMESTAMP, 'TALEXAND', CURRENT_TIMESTAMP);

commit;


















