package com.system.message.rule.header;

import static com.system.configuration.constants.Element.*;

public abstract interface DE043RuleHeader {
 
	// DE043 Header - Card Acceptor Name Location Rule Header

  	/***********************************************************************************
   	 ***********************************************************************************
   	 */	
	
	public static final String 	DE043_RULE_HEADER_REPORT_TITLE										= "DE043 Rule Header";
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_ID				= 43000;	 
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_FIELD			= 43;	 
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_SUBFIELD		= 0;
	
	public static final boolean CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_FIRE			= RULE_NOT_FIRED_B;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_FORMAT			= FIXED_FORMAT;	
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_MINIMUM_LENGTH	= 25;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_MAXIMUM_LENGTH	= 25;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_ENCODING		= EBCDIC_ENCODING;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_DATATYPE		= ALPHANUMERIC_SPECIAL_DATATYPE;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_SOURCE			= ASSOCIATION_FROM_SOURCE;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_DIRECTION		= ASSOCIATION_FROM_DIRECTION;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_EXISTENCE		= MANDATORY_PRESENCE;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_CHANGE			= ELEMENT_FIXED;
	
	public static final String 	CARD_ACCEPTOR_NAME_LOCATION_ADDRESS_043_RULE_HEADER_VALUE			= null;
	
	//--------------------------------------------------------------------------------------------------------------
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_ID					= 43000;	 
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_FIELD				= 43;	 
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_SUBFIELD			= 1;
	
	public static final boolean CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_FIRE				= RULE_NOT_FIRED_B;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_FORMAT				= FIXED_FORMAT;	
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_MINIMUM_LENGTH		= 13;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_MAXIMUM_LENGTH		= 13;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_ENCODING			= EBCDIC_ENCODING;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_DATATYPE			= ALPHANUMERIC_SPECIAL_DATATYPE;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_SOURCE				= ASSOCIATION_FROM_SOURCE;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_DIRECTION			= ASSOCIATION_FROM_DIRECTION;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_EXISTENCE			= MANDATORY_PRESENCE;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_CHANGE				= ELEMENT_FIXED;
	
	public static final String 	CARD_ACCEPTOR_NAME_LOCATION_CITY_043_RULE_HEADER_VALUE				= null;
	
	//--------------------------------------------------------------------------------------------------------------
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_ID				= 43000;	 
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_FIELD				= 43;	 
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_SUBFIELD			= 2;
	
	public static final boolean CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_FIRE				= RULE_NOT_FIRED_B;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_FORMAT			= FIXED_FORMAT;	
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_MINIMUM_LENGTH	= 2;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_MAXIMUM_LENGTH	= 2;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_ENCODING			= EBCDIC_ENCODING;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_DATATYPE			= ALPHANUMERIC_SPECIAL_DATATYPE;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_SOURCE			= ASSOCIATION_FROM_SOURCE;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_DIRECTION			= ASSOCIATION_FROM_DIRECTION;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_EXISTENCE			= MANDATORY_PRESENCE;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_CHANGE			= ELEMENT_FIXED;
	
	public static final String 	CARD_ACCEPTOR_NAME_LOCATION_STATE_043_RULE_HEADER_VALUE				= null;
	
	//--------------------------------------------------------------------------------------------------------------
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_ID				= 43000;	 
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_FIELD			= 43;	 
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_SUBFIELD		= 3;
	
	public static final boolean CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_FIRE			= RULE_NOT_FIRED_B;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_FORMAT			= FIXED_FORMAT;	
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_MINIMUM_LENGTH	= 2;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_MAXIMUM_LENGTH	= 2;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_ENCODING		= EBCDIC_ENCODING;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_DATATYPE		= ALPHANUMERIC_SPECIAL_DATATYPE;
	
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_SOURCE			= ASSOCIATION_FROM_SOURCE;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_DIRECTION		= ASSOCIATION_FROM_DIRECTION;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_EXISTENCE		= MANDATORY_PRESENCE;
	public static final int 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_CHANGE			= ELEMENT_FIXED;
	
	public static final String 	CARD_ACCEPTOR_NAME_LOCATION_COUNTRY_043_RULE_HEADER_VALUE			= null;
	
}
