delete from PROCESSING_IMPACT_TABLE;
insert into PROCESSING_IMPACT_TABLE values ( 0, CURRENT_DATE, 1, 0, 1, 1, 5, 'BASE I Processing'	, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into PROCESSING_IMPACT_TABLE values ( 0, CURRENT_DATE, 1, 0, 1, 1, 5, 'BASE II Processing'	, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
commit;
