delete from PROCESSOR_IMPACT_TABLE;
insert into PROCESSOR_IMPACT_TABLE values ( 0, CURRENT_DATE, 1, 0, 1, 1, 2, 'Acquirer', 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into PROCESSOR_IMPACT_TABLE values ( 0, CURRENT_DATE, 1, 0, 1, 1, 2, 'Issuer'  , 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
commit;
