delete from RELEASE_OVERVIEW_TABLE;
insert into RELEASE_OVERVIEW_TABLE values ( 0, 1, CURRENT_DATE  ,'Initial Publication'  , 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into RELEASE_OVERVIEW_TABLE values ( 0, 2, CURRENT_DATE  ,'Secondary Publication', 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into RELEASE_OVERVIEW_TABLE values ( 0, 3, CURRENT_DATE  ,'Third Publication'    , 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
commit;