delete from SUBSECTION_TABLE;
insert into SUBSECTION_TABLE values ( 0, 'Subsection 1.1 Africa Region Menu' 					, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 1.2 Americas Region Menu' 					, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 1.3 European Region Menu' 					, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 1.4 Middle East Region Menu' 				, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 1.5 Pacific Region Menu' 					, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 2.1 Africa Currency Menu' 					, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 2.2 Americas Currency Menu' 				, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 2.3 European Currency Menu' 				, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 2.4 Middle East Currency Menu' 			, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 2.5 Pacific Currency Menu' 				, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 3.1 Africa Clearing Menu' 					, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 3.2 Americas Clearing Menu' 				, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 3.3 European Clearing Menu' 				, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 3.4 Middle East Clearing Menu' 			, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 3.5 Pacific Clearing Menu' 				, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 4.1 Other Program Changes #1 Menu' 		, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 4.2 Other Program Changes #2 Menu' 		, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 4.3 Other Program Changes #3 Menu' 		, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 4.4 Other Program Changes #4 Menu' 		, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 4.5 Other Program Changes #5 Menu' 		, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 5.1 Additional System Impacts #1 Menu' 	, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 5.2 Additional System Impacts #2 Menu' 	, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 5.3 Additional System Impacts #3 Menu' 	, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 5.4 Additional System Impacts #4 Menu' 	, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SUBSECTION_TABLE values ( 0, 'Subsection 5.5 Additional System Impacts #5 Menu' 	, CURRENT_DATE, 1, 0, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
commit;