delete from SYSTEM_IMPACT_TABLE;
insert into SYSTEM_IMPACT_TABLE values ( 0, CURRENT_DATE, 1, 0, 1, 1, 2, 'BASE I'	, 1, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SYSTEM_IMPACT_TABLE values ( 0, CURRENT_DATE, 1, 0, 1, 1, 2, 'BASE II'	, 1, 1, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
commit;
