delete from DATABASE_PROPERTIES_TABLE;
insert into DATABASE_PROPERTIES_TABLE values ( 0, 'Driver Name 1', 'Server Name 1', '123.456.789.012', 'System Identifier 1', 'USERNAME', 'PASSWORD','TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into DATABASE_PROPERTIES_TABLE values ( 0, 'Driver Name 2', 'Server Name 2', '234.567.890.123', 'System Identifier 2', 'USERNAME', 'PASSWORD','TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into DATABASE_PROPERTIES_TABLE values ( 0, 'Driver Name 3', 'Server Name 3', '345.678.901.234', 'System Identifier 1', 'USERNAME', 'PASSWORD','TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
commit;