DROP TABLE PASSWORD_TABLE;

DROP SEQUENCE PASSWORD_TABLE_SEQUENCE;

CREATE TABLE PASSWORD_TABLE 
(
	 ID					NUMBER(04)		NOT NULL	
	,GROUP_ID			NUMBER(03)		NOT NULL	 
	,USER_ID			NUMBER(03)		NOT NULL	 
	,SEQ				NUMBER(03)		NOT NULL
	,USER_NAME			VARCHAR2(08)	NOT NULL
	,PASSWORD			VARCHAR2(08)	NOT NULL
	,DOMAIN				VARCHAR2(20)	NOT NULL
	,COMPUTER_NAME		VARCHAR2(07)	NOT NULL	 
	,REMEMBER_ME		NUMBER(01)		NOT NULL
	,PASSWORD_TYPE		NUMBER(01)		NOT NULL
	,FIRST_NAME			VARCHAR2(30)	NOT NULL
	,LAST_NAME			VARCHAR2(30)	NOT NULL
	,ACCOUNT_STATUS		NUMBER(01)		NOT NULL	 
	,LAST_ACCESS		TIMESTAMP(4)	NOT NULL
	,PASSWORD_CHANGE	TIMESTAMP(4)	NOT NULL
	,PASWORD_ATTEMPTS	NUMBER(01)		NOT NULL	 
  	,CREATE_USER		CHAR(8)			NOT NULL
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL
  	,MODIFY_USER		CHAR(8)			NOT NULL
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL
);

ALTER TABLE PASSWORD_TABLE ADD (
  CONSTRAINT PASSWORD_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE PASSWORD_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER PASSWORD_TABLE_TRIGGER 
BEFORE INSERT ON PASSWORD_TABLE 
FOR EACH ROW

BEGIN
  SELECT PASSWORD_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/