DROP TABLE TRACK2_TABLE;

DROP SEQUENCE TRACK2_TABLE_SEQUENCE;

CREATE TABLE TRACK2_TABLE 
(
   	 ID           					NUMBER(4)    	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER			VARCHAR2(19)	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER_SEQ		NUMBER(2)		NOT NULL   	
	,START_SENTINEL 				CHAR(1)			NOT NULL  
	,FIELD_SEPARATOR				CHAR(1)			NOT NULL 
	,EXPIRATION_DATE_YEAR			NUMBER(2)		NOT NULL
	,EXPIRATION_DATE_MONTH			NUMBER(2)		NOT NULL
	,SERVICE_CODE					NUMBER(3)		NOT NULL
	,PIN_VALIDATION_KEY_INDEX		NUMBER(1)		NOT NULL
	,PIN_VERIFICATION_VALUE			NUMBER(4)		NOT NULL
	,CARD_VERIFICATION_VALUE		NUMBER(3)		NOT NULL
	,END_SENTINEL					CHAR(1)			NOT NULL 
	,LONG_REDUNDANCY_CHECK			CHAR(1)			NOT NULL   	
   	,CREATE_USER					CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP				TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER					CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP				TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE TRACK2_TABLE ADD (
  CONSTRAINT TRACK2_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE TRACK2_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER TRACK2_TABLE_TRIGGER 
BEFORE INSERT ON TRACK2_TABLE 
FOR EACH ROW

BEGIN
  SELECT TRACK2_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/