DROP TABLE TRACK3_TABLE;

DROP SEQUENCE TRACK3_TABLE_SEQUENCE;

CREATE TABLE TRACK3_TABLE 
(
   	 ID           					NUMBER(4)    	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER			VARCHAR2(19)	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER_SEQ		NUMBER(2)		NOT NULL   	
	,START_SENTINEL 				CHAR(1)			NOT NULL  
	,FORMAT_CODE 					CHAR(2)			NOT NULL 
	,FIELD_SEPARATOR				CHAR(1)			NOT NULL 
	,COUNTRY_CODE					NUMBER(3)		NOT NULL
	,CURRENCY_CODE					NUMBER(3)		NOT NULL
	,CURRENCY_EXPONENT				NUMBER(1)		NOT NULL
	,AMOUNT_AUTHORIZED_PER_CYCLE	NUMBER(4)		NOT NULL
	,AMOUNT_REMAINING_THIS_CYCLE	NUMBER(4)		NOT NULL
	,CYCLE_BEGIN_YEAR				NUMBER(1)		NOT NULL
	,CYCLE_BEGIN_DAY				NUMBER(3)		NOT NULL
	,CYCLE_LENGTH					NUMBER(2)		NOT NULL
	,RETRY_COUNT					NUMBER(1)		NOT NULL
	,PIN_CONTROL_PARAMETERS			VARCHAR2(6)		NOT NULL
	,INTERCHANGE_CONTROLS			NUMBER(1)		NOT NULL
	,PAN_SERVICE_RESTRICTION		NUMBER(2)		NOT NULL
	,SAN1_SERVICE_RESTRICTION		NUMBER(2)		NOT NULL
	,SAN2_SERVICE_RESTRICTION		NUMBER(2)		NOT NULL
	,EXPIRATION_DATE_YEAR			NUMBER(2)		NOT NULL
	,EXPIRATION_DATE_MONTH			NUMBER(2)		NOT NULL
	,CARD_SEQUENCE_NUMBER			NUMBER(1)		NOT NULL
	,CARD_SECURITY_NUMBER			NUMBER(9)		NOT NULL
	,RELAY_MARKER					CHAR(1)			NOT NULL
	,CRYPTOGRAPHIC_CHECK_DIGITS		NUMBER(1)		NOT NULL
	,END_SENTINEL					CHAR(1)			NOT NULL 
	,LONG_REDUNDANCY_CHECK			CHAR(1)			NOT NULL 
  	,CREATE_USER					CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP				TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER					CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP				TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE TRACK3_TABLE ADD (
  CONSTRAINT TRACK3_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE TRACK3_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER TRACK3_TABLE_TRIGGER 
BEFORE INSERT ON TRACK3_TABLE 
FOR EACH ROW

BEGIN
  SELECT TRACK3_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/