delete from TRANSFORM2_TABLE;
insert into TRANSFORM2_TABLE values ( 0, 'TSYS Corporation' ,  'One TSys Way', 'Atlanta', 'GA','840','31901','7066492310','TALEXAND',SYS_EXTRACT_UTC(SYSTIMESTAMP),'TALEXAND',SYS_EXTRACT_UTC(SYSTIMESTAMP));
