DROP TABLE RULE_DETAIL_EDITOR_TABLE;

DROP SEQUENCE RULE_DETAIL_EDITOR_TABLE_SEQ;

CREATE TABLE RULE_DETAIL_EDITOR_TABLE 
(
   	 ID           		NUMBER(4)    	NOT NULL
  	,FIELD				NUMBER(3)    	NOT NULL
	,SUBFIELD			NUMBER(2)    	NOT NULL
	,FIRE				NUMBER(1)    	NOT NULL
  	,RULE_TYPE			NUMBER(2)    	NOT NULL
  	,RULE_GROUP			NUMBER(2)    	NOT NULL
  	,BIN_LEVEL			NUMBER(2)    	NOT NULL
  	,ACCOUNT_LEVEL		NUMBER(2)    	NOT NULL
  	,TRANSACTION_LEVEL	NUMBER(2)    	NOT NULL
  	,SEQ				NUMBER(2)    	NOT NULL
  	,POINTER			NUMBER(2)    	NOT NULL
  	,FIELD_VALUE		VARCHAR2(30)	NOT NULL
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE RULE_DETAIL_EDITOR_TABLE ADD (
  CONSTRAINT RULE_DETAIL_EDITOR_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE RULE_DETAIL_EDITOR_TABLE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER RULE_DETAIL_EDITOR_TABLE_TRIG 
BEFORE INSERT ON RULE_DETAIL_EDITOR_TABLE 
FOR EACH ROW

BEGIN
  SELECT RULE_DETAIL_EDITOR_TABLE_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/