DROP TABLE DUAL_RULE_HEADER_TABLE;

DROP SEQUENCE DUAL_RULE_HEADER_TABLE_SEQ;

CREATE TABLE DUAL_RULE_HEADER_TABLE 
(
   	 ID           		NUMBER(4)    	NOT NULL
  	,FIELD1				NUMBER(3)    	NOT NULL
	,SUBFIELD1			NUMBER(2)    	NOT NULL
	,FIRE1				NUMBER(1)    	NOT NULL
	,FORMAT1			NUMBER(1)    	NOT NULL
	,MINIMUM_LENGTH1	NUMBER(3)    	NOT NULL
	,MAXIMUM_LENGTH1	NUMBER(3)    	NOT NULL
  	,ENCODING1			NUMBER(2)    	NOT NULL
  	,DATATYPE1			NUMBER(2)    	NOT NULL
  	,SOURCE1			NUMBER(2)    	NOT NULL
  	,DIRECTION1			NUMBER(2)    	NOT NULL
  	,EXISTENCE1			NUMBER(2)    	NOT NULL
  	,CHANGE1			NUMBER(2)    	NOT NULL
  	,FIELD2				NUMBER(3)    	NOT NULL
	,SUBFIELD2			NUMBER(2)    	NOT NULL
	,FIRE2				NUMBER(1)    	NOT NULL
	,FORMAT2			NUMBER(1)    	NOT NULL
	,MINIMUM_LENGTH2	NUMBER(3)    	NOT NULL
	,MAXIMUM_LENGTH2	NUMBER(3)    	NOT NULL
  	,ENCODING2			NUMBER(2)    	NOT NULL
  	,DATATYPE2			NUMBER(2)    	NOT NULL
  	,SOURCE2			NUMBER(2)    	NOT NULL
  	,DIRECTION2			NUMBER(2)    	NOT NULL
  	,EXISTENCE2			NUMBER(2)    	NOT NULL
  	,CHANGE2			NUMBER(2)    	NOT NULL
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL		 
);

ALTER TABLE DUAL_RULE_HEADER_TABLE ADD (
  CONSTRAINT DUAL_RULE_HEADER_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE DUAL_RULE_HEADER_TABLE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DUAL_RULE_HEADER_TABLE_TRIGGER 
BEFORE INSERT ON DUAL_RULE_HEADER_TABLE 
FOR EACH ROW

BEGIN
  SELECT DUAL_RULE_HEADER_TABLE_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/