DROP TABLE DUAL_RULE_DETAIL_TABLE;

DROP SEQUENCE DUAL_RULE_DETAIL_TABLE_SEQ;

CREATE TABLE DUAL_RULE_DETAIL_TABLE 
(
   	 ID           		NUMBER(4)    	NOT NULL
  	,FIELD1				NUMBER(3)    	NOT NULL
	,SUBFIELD1			NUMBER(2)    	NOT NULL
	,FIRE1				NUMBER(1)    	NOT NULL
  	,RULE_TYPE1			NUMBER(2)    	NOT NULL
  	,RULE_GROUP1		NUMBER(2)    	NOT NULL
  	,BIN_LEVEL1			NUMBER(2)    	NOT NULL
  	,ACCOUNT_LEVEL1		NUMBER(2)    	NOT NULL
  	,TRANSACTION_LEVEL1	NUMBER(2)    	NOT NULL
  	,POINTER1			NUMBER(2)    	NOT NULL
  	,SEQ1				NUMBER(2)    	NOT NULL
  	,FIELD_VALUE1		VARCHAR2(30)	NOT NULL
  	,FIELD2				NUMBER(3)    	NOT NULL
	,SUBFIELD2			NUMBER(2)    	NOT NULL
	,FIRE2				NUMBER(1)    	NOT NULL
  	,RULE_TYPE2			NUMBER(2)    	NOT NULL
  	,RULE_GROUP2		NUMBER(2)    	NOT NULL
  	,BIN_LEVEL2			NUMBER(2)    	NOT NULL
  	,ACCOUNT_LEVEL2		NUMBER(2)    	NOT NULL
  	,TRANSACTION_LEVEL2	NUMBER(2)    	NOT NULL
  	,POINTER2			NUMBER(2)    	NOT NULL
  	,SEQ2				NUMBER(2)    	NOT NULL
  	,FIELD_VALUE2		VARCHAR2(30)	NOT NULL
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE DUAL_RULE_DETAIL_TABLE ADD (
  CONSTRAINT DUAL_RULE_DETAIL_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE DUAL_RULE_DETAIL_TABLE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DUAL_RULE_DTL_TABLE_TRIGGER 
BEFORE INSERT ON DUAL_RULE_DETAIL_TABLE 
FOR EACH ROW

BEGIN
  SELECT DUAL_RULE_DETAIL_TABLE_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/