DROP TABLE DUAL_ELEMENT_TABLE;

DROP SEQUENCE DUAL_ELEMENT_TABLE_SEQUENCE;

CREATE TABLE DUAL_ELEMENT_TABLE 
(
   	 ID           		NUMBER(4)    	NOT NULL
  	,FIELD1				NUMBER(3)    	NOT NULL
	,SUBFIELD1			NUMBER(2)    	NOT NULL
	,FORMAT1			NUMBER(2)    	NOT NULL
	,LENGTH1			NUMBER(3)    	NOT NULL
  	,ENCODING1			NUMBER(2)    	NOT NULL
  	,DATATYPE1			NUMBER(2)    	NOT NULL
  	,SOURCE1			NUMBER(2)    	NOT NULL
  	,DIRECTION1			NUMBER(2)    	NOT NULL
  	,EXISTENCE1			NUMBER(2)    	NOT NULL
  	,CHANGE1			NUMBER(2)    	NOT NULL
  	,FIELD_VALUE1		VARCHAR2(35)    NOT NULL
  	,FIELD2				NUMBER(3)    	NOT NULL
	,SUBFIELD2			NUMBER(2)    	NOT NULL
	,FORMAT2			NUMBER(2)    	NOT NULL
	,LENGTH2			NUMBER(3)    	NOT NULL
  	,ENCODING2			NUMBER(2)    	NOT NULL
  	,DATATYPE2			NUMBER(2)    	NOT NULL
  	,SOURCE2			NUMBER(2)    	NOT NULL
  	,DIRECTION2			NUMBER(2)    	NOT NULL
  	,EXISTENCE2			NUMBER(2)    	NOT NULL
  	,CHANGE2			NUMBER(2)    	NOT NULL
  	,FIELD_VALUE2		VARCHAR2(35)    NOT NULL
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE DUAL_ELEMENT_TABLE ADD (
  CONSTRAINT DUAL_ELEMENT_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE DUAL_ELEMENT_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER DUAL_ELEMENT_TABLE_TRIGGER 
BEFORE INSERT ON DUAL_ELEMENT_TABLE 
FOR EACH ROW

BEGIN
  SELECT DUAL_ELEMENT_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/