DROP TABLE VALIDATE_HEADER_TABLE;

DROP SEQUENCE VALIDATE_HEADER_TABLE_SEQUENCE;

CREATE TABLE VALIDATE_HEADER_TABLE 
(
   	 ID           		NUMBER(4)    	NOT NULL
  	,FIELD				NUMBER(3)    	NOT NULL
	,SUBFIELD			NUMBER(2)    	NOT NULL
	,FIRE				NUMBER(3)    	NOT NULL
	,MINIMUM_LENGTH		NUMBER(3)    	NOT NULL
	,MAXIMUM_LENGTH		NUMBER(3)    	NOT NULL
  	,ENCODING			NUMBER(3)    	NOT NULL
  	,DATATYPE			NUMBER(3)    	NOT NULL
  	,SOURCE				NUMBER(3)    	NOT NULL
  	,DIRECTION			NUMBER(3)    	NOT NULL
  	,EXISTENCE			NUMBER(3)    	NOT NULL
  	,CHANGE				NUMBER(3)    	NOT NULL
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL		 
);

ALTER TABLE VALIDATE_HEADER_TABLE ADD (
  CONSTRAINT VALIDATE_HEADER_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE VALIDATE_HEADER_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER VALIDATE_HEADER_TABLE_TRIGGER 
BEFORE INSERT ON VALIDATE_HEADER_TABLE 
FOR EACH ROW

BEGIN
  SELECT VALIDATE_HEADER_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/