DROP TABLE TRANSFORM2_TABLE;

DROP SEQUENCE TRANSFORM2_TABLE_SEQUENCE;

CREATE TABLE TRANSFORM2_TABLE 
(
   	 ID           			NUMBER(4)    	NOT NULL
  	,NAME					VARCHAR2(30)	NOT NULL
	,STREET					VARCHAR2(30)	NOT NULL
	,CITY					VARCHAR2(30)	NOT NULL
	,STATE					CHAR(2)			NOT NULL
  	,COUNTRY				CHAR(3)			NOT NULL
  	,ZIP_CODE				VARCHAR2(9)		NOT NULL
  	,PHONE_NUMBER			CHAR(10)		NOT NULL
  	,CREATE_USER			CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER			CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE TRANSFORM2_TABLE ADD (
  CONSTRAINT TRANSFORM2_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE TRANSFORM2_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER TRANSFORM2_TABLE_TRIGGER 
BEFORE INSERT ON TRANSFORM2_TABLE 
FOR EACH ROW

BEGIN
  SELECT TRANSFORM2_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/