DROP TABLE SCHEME_TABLE;

DROP SEQUENCE SCHEME_TABLE_SEQUENCE;

CREATE TABLE SCHEME_TABLE 
(
   	 ID           		NUMBER(4)    	NOT NULL
	,COMPANY			VARCHAR2(30)	NOT NULL
  	,TYPE_HELD			VARCHAR2(10)	NOT NULL
	,SYMBOL				VARCHAR2(5)		NOT NULL
  	,INDUSTRY			VARCHAR2(30)	NOT NULL
	,FOUNDED			NUMBER(4)		NOT NULL	
  	,FOUNDER			VARCHAR2(35)	NOT NULL
	,CITY				VARCHAR2(30)	NOT NULL	
	,STATE				VARCHAR2(2)		NOT NULL
  	,COUNTRY			VARCHAR2(3)		NOT NULL
  	,AREA_SERVED		VARCHAR2(10)	NOT NULL
	,KEY_PEOPLE			VARCHAR2(30)	NOT NULL	
	,PRODUCTS			VARCHAR2(30)	NOT NULL
  	,REVENUE			NUMBER(6)		NOT NULL
  	,OPERATING_INCOME	NUMBER(6)		NOT NULL
  	,NET_INCOME			NUMBER(6)		NOT NULL
  	,TOTAL_ASSETS		NUMBER(6)		NOT NULL
  	,TOTAL_EQUITY		NUMBER(6)		NOT NULL
  	,TOTAL_EMPLOYEES	NUMBER(6)		NOT NULL
  	,WEBSITE			VARCHAR2(30)	NOT NULL
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE SCHEME_TABLE ADD (
  CONSTRAINT SCHEME_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE SCHEME_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER SCHEME_TABLE_TRIGGER 
BEFORE INSERT ON SCHEME_TABLE 
FOR EACH ROW

BEGIN
  SELECT SCHEME_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/