delete from PASSWORD_TABLE;
insert into PASSWORD_TABLE values ( 0, 100, 150, 1, 'KFUENTES','secret01', 'MANAGER' ,'PB288L7', 1, 1, 'Kristine' , 'Fuentes'  , 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into PASSWORD_TABLE values ( 0, 100, 175, 1, 'TALEXAND','secret02', 'BUSINESS','PB288L8', 1, 1, 'Toussaint', 'Alexander', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into PASSWORD_TABLE values ( 0, 100, 200, 1, 'HTHOREAU','secret03', 'ENGINEER','PB288L9', 1, 1, 'Henry'    , 'Thoreau'  , 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
commit; 