DROP TABLE DATABASE_PROPERTIES_TABLE;

DROP SEQUENCE DATABASE_PROPERTIES_TABLE_SEQ;

CREATE TABLE DATABASE_PROPERTIES_TABLE 
(
   	 ID           			NUMBER(4)    	NOT NULL
	,DRIVER_NAME			VARCHAR2(30)	NOT NULL
	,SERVER_NAME			VARCHAR2(30)	NOT NULL
	,PORT_NUMBER			VARCHAR2(15)	NOT NULL
  	,SYSTEM_IDENTFIER		VARCHAR2(30)	NOT NULL
  	,USERNAME				CHAR(8)			NOT NULL
  	,PASSWORD				CHAR(8)			NOT NULL
  	,CREATE_USER			CHAR(8)			NOT NULL
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL
  	,MODIFY_USER			CHAR(8)			NOT NULL
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL
);

ALTER TABLE DATABASE_PROPERTIES_TABLE ADD (
  CONSTRAINT DATABASE_PROPERTIES_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE DATABASE_PROPERTIES_TABLE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DATABASE_PROPERTIES_TABLE_TRIG 
BEFORE INSERT ON DATABASE_PROPERTIES_TABLE 
FOR EACH ROW

BEGIN
  SELECT DATABASE_PROPERTIES_TABLE_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/