DROP TABLE FILE_PROPERTIES_TABLE;

DROP SEQUENCE FILE_PROPERTIES_TABLE_SEQ;

CREATE TABLE FILE_PROPERTIES_TABLE 
(
   	 ID           			NUMBER(4)    	NOT NULL
	,PROPERTIES_FILE		VARCHAR2(30)	NOT NULL
	,DEFAULT_PROPERTIES		VARCHAR2(30)	NOT NULL
	,PROPERTIES_LOCATION	VARCHAR2(30)	NOT NULL
	,INPUT_FILENAME			VARCHAR2(30)	NOT NULL
  	,OUTPUT_FILENAME		VARCHAR2(30)	NOT NULL
  	,XML_JSON_SWITCH		NUMBER(1)		NOT NULL
  	,ENCODING				VARCHAR2(6)		NOT NULL
  	,PATH_NAME				VARCHAR2(30)	NOT NULL
  	,FILE_NAME1				VARCHAR2(30)	NOT NULL
  	,FILE_INPUT_STREAM		VARCHAR2(30)	NOT NULL
  	,FILE_OUTPUT_STREAM		VARCHAR2(30)	NOT NULL
  	,CREATE_USER			CHAR(8)			NOT NULL
  	,CREATE_TIMESTAMP		TIMESTAMP(4)	NOT NULL
  	,MODIFY_USER			CHAR(8)			NOT NULL
  	,MODIFY_TIMESTAMP		TIMESTAMP(4)	NOT NULL
);

ALTER TABLE FILE_PROPERTIES_TABLE ADD (
  CONSTRAINT FILE_PROPERTIES_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE FILE_PROPERTIES_TABLE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FILE_PROPERTIES_TABLE_TRIG 
BEFORE INSERT ON FILE_PROPERTIES_TABLE 
FOR EACH ROW

BEGIN
  SELECT FILE_PROPERTIES_TABLE_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/