DROP TABLE CHECKING_CHARGE_TABLE;

DROP SEQUENCE CHECKING_CHARGE_TABLE_SEQUENCE;

CREATE TABLE CHECKING_CHARGE_TABLE 
(
   	 ID           					NUMBER(4)    	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER			VARCHAR2(19)	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER_SEQ		NUMBER(2)		NOT NULL 
  	,CLOSING_DATE					DATE			NOT NULL
  	,BANK_NAME						VARCHAR2(30)	NOT NULL
  	,ASSOCIATION_NAME				VARCHAR2(30)	NOT NULL
  	,PURCHASE_APR					NUMBER(8)		NOT NULL
  	,PURCHASE_FCR					NUMBER(8)		NOT NULL
  	,PURCHASE_ADB					NUMBER(8)		NOT NULL
  	,ADVANCE_APR					NUMBER(8)		NOT NULL
  	,ADVANCE_FCR					NUMBER(8)		NOT NULL
  	,ADVANCE_ADB					NUMBER(8)		NOT NULL  	
  	,COMPOSITE_APR					NUMBER(8)		NOT NULL
   	,TOTAL_FEES_CHARGED				NUMBER(8)		NOT NULL
   	,PURCHASE_VARIABLE_APR			NUMBER(8)		NOT NULL
  	,PURCHASE_BALANCE_SUBJECT		NUMBER(8)		NOT NULL
  	,PURCHASE_DAYS_BILLING_CYCLE	NUMBER(8)		NOT NULL
 	,PURCHASE_INTEREST_CHARGE		NUMBER(8)		NOT NULL  	
  	,ADVANCE_VARIABLE_APR			NUMBER(8)		NOT NULL
  	,ADVANCE_BALANCE_SUBJECT		NUMBER(8)		NOT NULL
  	,ADVANCE_DAYS_BILLING_CYCLE		NUMBER(8)		NOT NULL
 	,ADVANCE_INTEREST_CHARGE		NUMBER(8)		NOT NULL  
    ,TOTAL_FEES_CHARGED_YTD			NUMBER(8)		NOT NULL
    ,TOTAL_INTEREST_CHARGED_YTD		NUMBER(8)		NOT NULL
   	,CREATE_USER					CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP				TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER					CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP				TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE CHECKING_CHARGE_TABLE ADD (
  CONSTRAINT CHECKING_CHARGE_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE CHECKING_CHARGE_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER CHECKING_CHARGE_TABLE_TRIGGER 
BEFORE INSERT ON CHECKING_CHARGE_TABLE 
FOR EACH ROW

BEGIN
  SELECT CHECKING_CHARGE_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/