DROP TABLE CHECKING_DETAIL_TABLE;

DROP SEQUENCE CHECKING_DETAIL_TABLE_SEQUENCE;

CREATE TABLE CHECKING_DETAIL_TABLE 
(
   	 ID           				NUMBER(4)    	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER		VARCHAR2(19)	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER_SEQ	NUMBER(2)		NOT NULL 
  	,CLOSING_DATE				DATE			NOT NULL
  	,BANK_NAME					VARCHAR2(30)	NOT NULL
  	,ASSOCIATION_NAME			VARCHAR2(30)	NOT NULL
  	,TRANSACTION_DATE			DATE			NOT NULL
  	,POSTING_DATE				DATE			NOT NULL
  	,REFERENCE_NUMBER			CHAR(10)		NOT NULL
  	,PRODUCT_DESCRIPTION		VARCHAR2(30)	NOT NULL
	,CREDIT_AMOUNT				NUMBER(8)    	NOT NULL
	,CHARGE_AMOUNT				NUMBER(8)    	NOT NULL
   	,CREATE_USER				CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP			TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER				CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP			TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE CHECKING_DETAIL_TABLE ADD (
  CONSTRAINT CHECKING_DETAIL_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE CHECKING_DETAIL_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER CHECKING_DETAIL_TABLE_TRIGGER 
BEFORE INSERT ON CHECKING_DETAIL_TABLE 
FOR EACH ROW

BEGIN
  SELECT CHECKING_DETAIL_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/