DROP TABLE CHECKING_SUMMARY_TABLE;

DROP SEQUENCE CHECKING_SUMMARY_TABLE_SEQUENCE;

CREATE TABLE CHECKING_SUMMARY_TABLE 
(
   	 ID           				NUMBER(4)    	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER		VARCHAR2(19)	NOT NULL
   	,PRIMARY_ACCOUNT_NUMBER_SEQ	NUMBER(2)		NOT NULL 
  	,CLOSING_DATE				DATE			NOT NULL
  	,BANK_NAME					VARCHAR2(30)	NOT NULL
  	,ASSOCIATION_NAME			VARCHAR2(30)	NOT NULL
 	,CREDIT_LINE				NUMBER(8)    	NOT NULL
 	,AVAILABLE_CREDIT			NUMBER(8)    	NOT NULL
 	,PREVIOUS_BALANCE			NUMBER(8)    	NOT NULL
 	,CREDITS					NUMBER(8)    	NOT NULL
 	,PAYMENTS					NUMBER(8)    	NOT NULL
 	,PURCHASES					NUMBER(8)    	NOT NULL
 	,CHARGES					NUMBER(8)    	NOT NULL
 	,CASH_ADVANCES				NUMBER(8)    	NOT NULL
 	,FINANACE_CHARGE			NUMBER(8)    	NOT NULL
 	,NEW_BALANCE				NUMBER(8)    	NOT NULL
   	,CREATE_USER				CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP			TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER				CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP			TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE CHECKING_SUMMARY_TABLE ADD (
  CONSTRAINT CHECKING_SUMMARY_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE CHECKING_SUMMARY_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER CHECKING_SUMMARY_TABLE_TRIGGER 
BEFORE INSERT ON CHECKING_SUMMARY_TABLE 
FOR EACH ROW

BEGIN
  SELECT CHECKING_SUMMARY_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/