DROP TABLE INVOICE_PART2_TABLE;

DROP SEQUENCE INVOICE_PART2_TABLE_SEQUENCE;

CREATE TABLE INVOICE_PART2_TABLE 
(
   	 ID           						NUMBER(4)    	NOT NULL
	,ACQUIRER_IDENTIFIER				NUMBER(11)    	NOT NULL
	,MERCHANT_IDENTIFIER				VARCHAR2(15)   	NOT NULL
	,TERMINAL_IDENTIFICATION			VARCHAR2(8)    	NOT NULL
	,INTERFACE_DEVICE_SERIAL_NUMBER		VARCHAR2(8)    	NOT NULL
	,TERMINAL_TYPE						NUMBER(2)    	NOT NULL
	,TERMINAL_COUNTRY_CODE				NUMBER(3)    	NOT NULL
	,COUNTRY_CODE						NUMBER(3)    	NOT NULL
	,CURRENCY_CODE						NUMBER(3)    	NOT NULL
	,FORM_FACTOR_INDICATOR				NUMBER(4)    	NOT NULL
	,POINT_OF_SERVICE_ENTRY_MODE		NUMBER(2)    	NOT NULL
	,TRANSACTON_TYPE					NUMBER(2)    	NOT NULL
	,TRANSACTION_DATE					NUMBER(6)    	NOT NULL
	,TRANSACTION_TIME					NUMBER(6)    	NOT NULL
  	,CREATE_USER						CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP					TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER						CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP					TIMESTAMP(4)	NOT NULL	
);

ALTER TABLE INVOICE_PART2_TABLE ADD (
  CONSTRAINT INVOICE_PART2_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE INVOICE_PART2_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER INVOICE_PART2_TABLE_TRIGGER 
BEFORE INSERT ON INVOICE_PART2_TABLE 
FOR EACH ROW

BEGIN
  SELECT INVOICE_PART2_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/