delete from SCREEN_TABLE;
insert into SCREEN_TABLE values ( 0, 100, 150, 1, 'Menu Name 1', 'Screen Name 1', 1,0,1,0,'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SCREEN_TABLE values ( 0, 100, 175, 1, 'Menu Name 2', 'Screen Name 2', 0,1,0,1,'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
insert into SCREEN_TABLE values ( 0, 100, 190, 1, 'Menu Name 3', 'Screen Name 3', 1,0,1,0,'TALEXAND',CURRENT_TIMESTAMP,'TALEXAND',CURRENT_TIMESTAMP);
commit;