DROP TABLE CARD_VERIFICATION_TABLE;

DROP SEQUENCE CARD_VERIFICATION_TABLE_SEQUENCE;

CREATE TABLE CARD_VERIFICATION_TABLE 
(
   	 ID           				NUMBER(4)    	NOT NULL
  	,LOW_BIN_RANGE_NUMBER		VARCHAR2(19)	NOT NULL
  	,HIGH_BIN_RANGE_NUMBER		VARCHAR2(19)	NOT NULL
	,CVV1						NUMBER(1)		NOT NULL
	,CVV2						NUMBER(1)		NOT NULL
	,ICVV						NUMBER(1)		NOT NULL
	,DCVV						NUMBER(1)		NOT NULL
  	,CREATE_USER				CHAR(8)			NOT NULL
  	,CREATE_TIMESTAMP			TIMESTAMP(4)	NOT NULL
  	,MODIFY_USER				CHAR(8)			NOT NULL
  	,MODIFY_TIMESTAMP			TIMESTAMP(4)	NOT NULL
);

ALTER TABLE CARD_VERIFICATION_TABLE ADD (
  CONSTRAINT CARD_VERIFICATION_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE CARD_VERIFICATION_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER CARD_VERIFICATION_TABLE_TRIGGER 
BEFORE INSERT ON CARD_VERIFICATION_TABLE 
FOR EACH ROW

BEGIN
  SELECT CARD_VERIFICATION_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/