DROP TABLE DOMESTIC_LIMIT_TABLE;

DROP SEQUENCE DOMESTIC_LIMIT_TABLE_SEQUENCE;

CREATE TABLE DOMESTIC_LIMIT_TABLE 
(
   	 ID           				NUMBER(4)    	NOT NULL
  	,LOW_BIN_RANGE_NUMBER		VARCHAR2(19)	NOT NULL
  	,HIGH_BIN_RANGE_NUMBER		VARCHAR2(19)	NOT NULL
  	,BIN_LENGTH					NUMBER(2)		NOT NULL
  	,ACCOUNT_NUMBER_LENGTH		NUMBER(2)		NOT NULL
	,SINGLE_MAXIMUM_ADV_AMOUNT	NUMBER(6)		NOT NULL
	,SINGLE_MAXIMUM_ATM_AMOUNT	NUMBER(6)		NOT NULL
	,SINGLE_MAXIMUM_BCK_AMOUNT	NUMBER(6)		NOT NULL
	,SINGLE_MAXIMUM_POS_AMOUNT	NUMBER(6)		NOT NULL
	,SINGLE_MAXIMUM_TRN_AMOUNT	NUMBER(6)		NOT NULL
	,DAILY_MAXIMUM_ADV_AMOUNT	NUMBER(6)		NOT NULL
	,DAILY_MAXIMUM_ATM_AMOUNT	NUMBER(6)		NOT NULL
	,DAILY_MAXIMUM_BCK_AMOUNT	NUMBER(6)		NOT NULL
	,DAILY_MAXIMUM_POS_AMOUNT	NUMBER(6)		NOT NULL
	,DAILY_MAXIMUM_TRN_AMOUNT	NUMBER(6)		NOT NULL
	,DAILY_MAXIMUM_ADV_NUMBER	NUMBER(2)		NOT NULL
	,DAILY_MAXIMUM_ATM_NUMBER	NUMBER(2)		NOT NULL
	,DAILY_MAXIMUM_BCK_NUMBER	NUMBER(2)		NOT NULL
	,DAILY_MAXIMUM_POS_NUMBER	NUMBER(2)		NOT NULL
	,DAILY_MAXIMUM_TRN_NUMBER	NUMBER(2)		NOT NULL
	,DAILY_MAXIMUM_DECLINES		NUMBER(2)		NOT NULL
	,DAILY_MAXIMUM_BAD_PINS		NUMBER(2)		NOT NULL
  	,CREATE_USER				CHAR(8)			NOT NULL
  	,CREATE_TIMESTAMP			TIMESTAMP(4)	NOT NULL
  	,MODIFY_USER				CHAR(8)			NOT NULL
  	,MODIFY_TIMESTAMP			TIMESTAMP(4)	NOT NULL
);

ALTER TABLE DOMESTIC_LIMIT_TABLE ADD (
  CONSTRAINT DOMESTIC_LIMIT_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE DOMESTIC_LIMIT_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER DOMESTIC_LIMIT_TABLE_TRIGGER 
BEFORE INSERT ON DOMESTIC_LIMIT_TABLE 
FOR EACH ROW

BEGIN
  SELECT DOMESTIC_LIMIT_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/