DROP TABLE SIMULATION_TABLE;

DROP SEQUENCE SIMULATION_TABLE_SEQUENCE;

CREATE TABLE SIMULATION_TABLE 
(
   	 ID           					NUMBER(4)    	NOT NULL
   	,PRIMARY_ACCCOUNT_NUMBER		VARCHAR2(19)	NOT NULL
   	,TRANSACTION_TYPE				CHAR(02)		NOT NULL
   	,ACCOUNT_FROM_TYPE				CHAR(02)		NOT NULL 
  	,ACCOUNT_TO_TYPE				CHAR(02)		NOT NULL
	,TRANSACTION_AMOUNT				NUMBER(12)		NOT NULL
	,EXPIRATION_DATE				CHAR(04)		NOT NULL
	,MERCHANT_CATEGORY_CODE			CHAR(04)		NOT NULL
  	,ACQUIRE_INST_COUNTRY_CODE		CHAR(03)		NOT NULL
  	,FORWARD_INST_COUNTRY_CODE		CHAR(03)		NOT NULL
  	,TRANSACTION_ENTRY_MODE			CHAR(02)		NOT NULL
  	,PIN_ENTRY_MODE					CHAR(01)		NOT NULL
   	,POS_CONDITION_CODE				CHAR(02)		NOT NULL
   	,TRANSACTION_FEE_AMOUNT			VARCHAR2(09)	NOT NULL 
  	,RESPONSE_CODE					CHAR(03)		NOT NULL
	,TRANSACTION_CURRENCY_CODE		CHAR(03)		NOT NULL
	,ACCOUNT_TYPE					CHAR(02)		NOT NULL
	,AMOUNT_TYPE					CHAR(02)		NOT NULL
  	,CURRENCY_CODE					CHAR(03)		NOT NULL
  	,AMOUNT							CHAR(12)		NOT NULL
  	,NETWORK_MANAGEMENT_CODE		CHAR(03)		NOT NULL
  	
  	,CREATE_USER					CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP				TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER					CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP				TIMESTAMP(4)	NOT NULL
);

ALTER TABLE SIMULATION_TABLE ADD (
  CONSTRAINT SIMULATION_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE SIMULATION_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER SIMULATION_TABLE_TRIGGER 
BEFORE INSERT ON SIMULATION_TABLE 
FOR EACH ROW

BEGIN
  SELECT SIMULATION_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/