DROP TABLE ADDRESS_TABLE;

DROP SEQUENCE ADDRESS_TABLE_SEQUENCE;

CREATE TABLE ADDRESS_TABLE 
(
   	 ID           		NUMBER(4)    	NOT NULL
	,STREET				VARCHAR2(30)	NOT NULL
	,CITY				VARCHAR2(30)	NOT NULL
	,STATE				CHAR(2)			NOT NULL
  	,COUNTRY			CHAR(3)			NOT NULL
  	,ZIP_CODE			VARCHAR2(9)		NOT NULL
  	,PHONE_NUMBER		CHAR(10)		NOT NULL
  	,CREATE_USER		CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP	TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER		CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP	TIMESTAMP(4)	NOT NULL		
);

ALTER TABLE ADDRESS_TABLE ADD (
  CONSTRAINT ADDRESS_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE ADDRESS_TABLE_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER ADDRESS_TABLE_TRIGGER 
BEFORE INSERT ON ADDRESS_TABLE 
FOR EACH ROW

BEGIN
  SELECT ADDRESS_TABLE_SEQUENCE.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/