CREATE TABLE emp99 (
   	 ID           	INT 			NOT NULL AUTO_INCREMENT
  	,NAME			VARCHAR(30)		NOT NULL
	,SALARY			DOUBLE(6,2)		NOT NULL
  	,DESIGNATION  	VARCHAR(50)  	NOT NULL
  	,PRIMARY KEY ( ID )
);
