DROP TABLE ISSUER_MASTER_FILE_TABLE;

DROP SEQUENCE ISSUER_MASTER_FILE_TABLE_SEQ;

CREATE TABLE ISSUER_MASTER_FILE_TABLE 
(
   	 ID           					NUMBER(4)    	NOT NULL
   	,INTL_BANK_ACCOUNT_NUMBER		VARCHAR2(34)	NOT NULL
   	,BANK_IDENTIFIER_CODE			VARCHAR2(11)	NOT NULL
   	,BANK_IDENTIFICATION_NUMBER		NUMBER(6)		NOT NULL 
  	,FIRST_NAME						VARCHAR2(30)	NOT NULL
	,MIDDLE_NAME					VARCHAR2(30)	NOT NULL
	,LAST_NAME						VARCHAR2(30)	NOT NULL
	,SOCIAL_SECURITY				CHAR(9)			NOT NULL
  	,PRIMARY_ACCOUNT_NUMBER			VARCHAR2(19)	NOT NULL
  	,PRIMARY_ACCOUNT_NUMBER_SEQ		NUMBER(2)		NOT NULL
  	,ASSOCIATION_NAME				VARCHAR2(30)	NOT NULL
  	,BANK_NAME						VARCHAR2(30)	NOT NULL
  	,BRAND_NAME						VARCHAR2(30)	NOT NULL
  	,CARD_EXPIRATION_DATE			DATE			NOT NULL
  	,CARD_VERIFICATION_VALUE		NUMBER(3)		NOT NULL
  	,CREATE_USER					CHAR(8)			NOT NULL	 
  	,CREATE_TIMESTAMP				TIMESTAMP(4)	NOT NULL	 
  	,MODIFY_USER					CHAR(8)			NOT NULL	 
  	,MODIFY_TIMESTAMP				TIMESTAMP(4)	NOT NULL
);

ALTER TABLE ISSUER_MASTER_FILE_TABLE ADD (
  CONSTRAINT ISSUER_MASTER_FILE_TABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE ISSUER_MASTER_FILE_TABLE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER ISS_MASTER_FILE_TABLE_TRIGGER
BEFORE INSERT ON ISSUER_MASTER_FILE_TABLE 
FOR EACH ROW

BEGIN
  SELECT ISSUER_MASTER_FILE_TABLE_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;
/